package com.letv.autoapk.player;

/**
 * Created by heyuekuai on 16/1/4.
 */
public interface ISplayerController {
	int SCREEN_ORIENTATION_PORTRAIT = 2000;
	int SCREEN_ORIENTATION_LANDSCAPE = 2001;
	int SCREEN_ORIENTATION_REVERSE_LANDSCAPE = 2008;
	int SCREEN_ORIENTATION_REVERSE_PORTRAIT = 2009;
	int SCREEN_ORIENTATION_USER_LANDSCAPE = 2011;
	int SCREEN_ORIENTATION_USER_PORTRAIT = 2012;
	int SHOW_FLOATING_VIEW = 2020;
	int HIDE_FLOATING_VIEW = 2021;
	int change_volume = 2002;

}
